import axios from "axios";
import { cookies } from 'next/headers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({children}) {


  return (
      <html lang="en">
      <body>{children}</body>
      </html>
  )
}
